# Generated by Django 4.2.11 on 2026-01-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployPlan',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('req', models.JSONField()),
                ('artifacts', models.JSONField(default=list)),
                ('commands', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('targets', models.JSONField(default=list)),
                ('logs', models.JSONField(default=list)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=50)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('user', models.CharField(default='root', max_length=255)),
                ('auth_method', models.CharField(choices=[('key', 'SSH Key'), ('password', 'Password')], default='key', max_length=20)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('key_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
