# Generated by Django 4.2.11 on 2026-01-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prometheus_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('ark_base_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('ark_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('ark_model_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
