# Generated by Django 4.2.11 on 2026-01-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('es_hosts', models.CharField(blank=True, max_length=1024, null=True)),
                ('es_username', models.CharField(blank=True, max_length=255, null=True)),
                ('es_password', models.CharField(blank=True, max_length=255, null=True)),
                ('index_pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('slack_webhook_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('poll_interval_seconds', models.IntegerField(default=60)),
                ('alert_keywords', models.JSONField(default=list)),
                ('ignore_keywords', models.JSONField(default=list)),
                ('record_only_keywords', models.JSONField(default=list)),
            ],
        ),
    ]
