# Generated by Django 4.2.11 on 2026-01-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitorconfig',
            old_name='es_password',
            new_name='s3_access_key',
        ),
        migrations.RenameField(
            model_name='monitorconfig',
            old_name='es_username',
            new_name='s3_bucket',
        ),
        migrations.RenameField(
            model_name='monitorconfig',
            old_name='index_pattern',
            new_name='s3_secret_key',
        ),
        migrations.RemoveField(
            model_name='monitorconfig',
            name='es_hosts',
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='k8s_kubeconfig',
            field=models.TextField(blank=True, help_text='Kubeconfig content (YAML). If empty, use in-cluster config or default.', null=True),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='k8s_namespace',
            field=models.CharField(default='default', help_text='K8s Namespace to watch', max_length=255),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='retention_days',
            field=models.IntegerField(default=3, help_text='Days to keep logs locally before S3 upload'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='s3_endpoint',
            field=models.CharField(blank=True, help_text='Optional custom endpoint', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='s3_region',
            field=models.CharField(default='us-east-1', max_length=50),
        ),
    ]
