# Generated by Django 4.2.11 on 2026-01-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_rename_es_password_monitorconfig_s3_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='s3_archive_enabled',
            field=models.BooleanField(default=False, help_text='Enable archiving logs to S3'),
        ),
    ]
