# Generated by Django 4.2.11 on 2026-08-25 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import security.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDoc',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('vector_id', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'knowledge_docs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stage', models.CharField(default='init', max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scan_sessions',
            },
        ),
        migrations.CreateModel(
            name='SecurityTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(default='custom', max_length=20)),
                ('platform_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(default='auto', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('target', models.CharField(max_length=500)),
                ('scope', models.JSONField(default=dict)),
                ('progress', models.IntegerField(default=0)),
                ('vuln_count', models.JSONField(default=security.models._vuln_count_default)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=500)),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField()),
                ('proof', models.TextField(blank=True, null=True)),
                ('steps', models.JSONField(blank=True, default=list, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(default='')),
                ('cve', models.CharField(blank=True, max_length=20, null=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('references', models.JSONField(blank=True, default=list, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='new', max_length=20)),
                ('found_by', models.CharField(max_length=50)),
                ('found_at', models.DateTimeField()),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities', to='security.scansession')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='security.securitytask')),
            ],
            options={
                'db_table': 'vulnerabilities',
            },
        ),
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('edited_content', models.TextField(blank=True, null=True)),
                ('target_info', models.JSONField(blank=True, default=dict, null=True)),
                ('vuln_summary', models.JSONField(blank=True, default=dict, null=True)),
                ('vuln_count', models.JSONField(default=security.models._vuln_count_default)),
                ('platform_report_id', models.CharField(blank=True, max_length=200, null=True)),
                ('platform_feedback', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('reward', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='security.securitytask')),
            ],
            options={
                'db_table': 'security_reports',
            },
        ),
        migrations.CreateModel(
            name='ScanTool',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('command', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('output_lines', models.JSONField(blank=True, default=list, null=True)),
                ('finding_count', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='security.scansession')),
            ],
            options={
                'db_table': 'scan_tools',
            },
        ),
        migrations.AddField(
            model_name='scansession',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_session', to='security.securitytask'),
        ),
        migrations.CreateModel(
            name='GuidedSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stage', models.CharField(default='recon', max_length=30)),
                ('is_completed', models.BooleanField(default=False)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guided_session', to='security.securitytask')),
            ],
            options={
                'db_table': 'guided_sessions',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('type', models.CharField(default='text', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('command', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='security.guidedsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=500)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('extra', models.JSONField(blank=True, default=dict, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='security.scansession')),
            ],
            options={
                'db_table': 'assets',
            },
        ),
    ]
