# Generated by Django 4.2.11 on 2026-04-07 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_ops', '0009_incident_last_received_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(blank=True, db_index=True, default='', help_text='关联 Agent 运行实例', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(help_text='故障总结（给人看的摘要）')),
                ('evidence_chain', models.JSONField(default=list, help_text='证据链：工具调用摘要、citation、指标指针等')),
                ('proposed_actions', models.JSONField(default=list, help_text='拟执行动作列表，如 {type: shell|http|deploy|db_sql, payload: ...}')),
                ('risk_notes', models.TextField(blank=True, default='', help_text='风险与回滚提示')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executing', 'Executing'), ('executed', 'Executed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True, default='')),
                ('execution_result', models.JSONField(blank=True, default=dict)),
                ('execution_error', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_smart_tickets', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_tickets', to='ai_ops.incident')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
