# Generated by Django 4.2.11 on 2026-04-07 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_ops', '0010_smart_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.CharField(blank=True, db_index=True, default='', help_text='LangGraph / Celery 运行实例，对应 SSE 频道 agent:run:{run_id}', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('executed', 'Executed'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32)),
                ('summary', models.TextField(default='', help_text='故障总结（面向审批人）')),
                ('root_cause', models.TextField(default='', help_text='根因分析')),
                ('proposed_action', models.TextField(default='', help_text='修复方案：可执行 shell / kubectl / API 调用说明等（仅建议，未经批准不得执行）')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True, default='')),
                ('execution_result', models.JSONField(blank=True, default=dict)),
                ('execution_error', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tickets', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ai_ops.incident')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SmartTicket',
        ),
    ]
