# Generated by Django 4.2.11 on 2026-04-24 08:46

from django.db import migrations, models


def _zero_line_caps(apps, schema_editor):
    TrafficDashboardConfig = apps.get_model("traffic", "TrafficDashboardConfig")
    TrafficDashboardConfig.objects.filter(pk=1).update(redis_max_lines=0, dashboard_fetch_max_lines=0)


class Migration(migrations.Migration):

    dependencies = [
        ("traffic", "0006_trafficminuterollup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficdashboardconfig",
            name="dashboard_fetch_max_lines",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 = read full Redis list when loading raw; N>0 = cap lines per fetch.",
            ),
        ),
        migrations.AlterField(
            model_name="trafficdashboardconfig",
            name="redis_max_lines",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 = no LTRIM (unlimited list length); N>0 = keep at most N lines after push.",
            ),
        ),
        migrations.RunPython(_zero_line_caps, migrations.RunPython.noop),
    ]
