# Generated by Django 4.2.11 on 2026-01-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('database', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_source', models.CharField(default='admin', max_length=255)),
                ('replica_set', models.CharField(blank=True, max_length=255, null=True)),
                ('mongo_hosts', models.TextField(blank=True, null=True)),
                ('use_ssl', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('task_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('config', models.JSONField()),
                ('status', models.CharField(default='stopped', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
