# Generated by Django 4.2.11 on 2026-01-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctask',
            name='state',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='synctask',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
